---
# tasks file for ufw
- name:  Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present 
  when: ansible_os_family =="Debian"

- name: Allow HTTP (80)
  ufw:
    rule: allow
    port: '80'
    proto: tcp
    
- name: Allow HTTPS (443)
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
    policy: allow