---
# handlers file for apache
- name: restart apache
  ansible.builtin.service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"
- name: restart apache
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"